apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
    containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
    volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
    resources:
        requests:
          cpu: "100m"      # Request 100 millicores (0.1 CPU)
          memory: "128Mi"  # Request 128MB memory
        limits:
          cpu: "500m"      # Limit to 500 millicores (0.5 CPU)
          memory: "256Mi"  # Limit to 256MB memory
