apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Interactive Nginx Page</title>
    </head>
    <body>
        <h1>Hello from Nginx!</h1>
    </body>
    </html>