apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: ai
data:
  grafana.ini: |
    [server]
    # The http port to bind to
    http_port = 3000

    [security]
    # Admin user credentials
    admin_user = admin
    admin_password = admin  # Change this to a more secure password