apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-data
  namespace: ai
  labels:
    app: grafana
data:
  anomaly-dashboard.json: |
    {
      "annotations": {
        "list": []
      },
      "panels": [
        {
          "datasource": "Prometheus",
          "id": 1,
          "title": "Anomaly Detection",
          "type": "graph",
          "targets": [
            {
              "expr": "anomaly_detection_expression",
              "interval": "",
              "legendFormat": "Anomaly"
            }
          ]
        }
      ]
    }
